# Schema for Stanford SearchStax settings configuration.
stanford_searchstax.settings:
  type: config_object
  label: 'Stanford SearchStax settings'
  mapping:
    endpoint:
      type: string
      label: 'SearchStax Endpoint'
